name: linux/amd64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Pull Latest Linux Base Image
        run: docker pull debian:stretch-slim

      - name: Build Linux Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          no-cache: true

      - name: Test Linux Image
        run: docker run --rm ghcr.io/${{ env.IMAGE_NAME }}:latest /app/ll-tests/gamesvr-svencoop.sh

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
